name: 'Rebol-AGG CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.21.2

    - name: Build 32bit Rebol/AGG extension
      run: ./siskin Rebol-AGG.nest -o ./agg-windows-x86.rebx --msvc agg-windows-x86

    - name: Build 64bit Rebol/AGG extension
      run: ./siskin Rebol-AGG.nest -o ./agg-windows-x64.rebx --msvc agg-windows-x64

    - name: Install Rebol
      uses: oldes/install-rebol@v0.21.0

    - name: Minimal Rebol/AGG extension test
      run:  ./rebol ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-AGG-Windows-CI-${{github.run_id}}
        path: ./*.rebx

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.21.2

    - name: Build 64bit Rebol/AGG extension
      run: ./siskin Rebol-AGG.nest -o ./agg-linux-x64.rebx --gzip agg-linux-x64

    - name: Install Rebol
      uses: oldes/install-rebol@v0.21.0

    - name: Minimal Rebol/AGG extension test
      run:  ./rebol ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-AGG-Linux-CI-${{github.run_id}}
        path: ./*.gz

  mac-arm64:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.21.2

    - name: Install freetype
      run: brew install freetype

    - name: Build 64bit Rebol/AGG extension
      run: ./siskin Rebol-AGG.nest -o ./agg-macos-arm64.rebx --gzip agg-macos-arm64

    - name: Install Rebol
      uses: oldes/install-rebol@v0.21.0

    - name: Minimal Rebol/AGG extension test
      run:  ./rebol ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-AGG-macOS-CI-${{github.run_id}}
        path: ./*.gz

  mac-x86_64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Intel Homebrew & deps
      run: |
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "/usr/local/bin/brew" >> $GITHUB_PATH
        arch -x86_64 brew install freetype
        ls -la /usr/local/include
        ls -la /usr/local/opt
   
    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.21.2
      with:
        arch: x86_64

    - name: Build 64bit Rebol/AGG extension
      run: arch -x86_64 ./siskin Rebol-AGG.nest -o ./agg-macos-x64.rebx --gzip agg-macos-x64
    
    - name: Verify
      run: |
        file ./agg-macos-x64.rebx  # x86_64 Mach-O
        otool -L ./agg-macos-x64.rebx

    - name: Install Rebol
      uses: oldes/install-rebol@v0.21.0
      with:
        arch: x86_64

    - name: Minimal Rebol/AGG extension test
      run:  arch -x86_64 ./rebol ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-AGG-macOS-Intel-CI-${{github.run_id}}
        path: ./*.gz

#  Haiku-x86:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Download Haiku Rebol-dev container
#        run: docker pull docker.io/oldes/rebol-dev:haiku-x86
#
#      - name: Build all Rebol/AGG for Haiku OS x86
#        run: docker run --rm -v $PWD:/siskin oldes/rebol-dev:haiku-x86 bash -c 'cd /siskin; rebol siskin.r3 Rebol-AGG.nest agg-haiku-x86'
#
#      - name: Compress result before uploading
#        run: |
#          sudo mv ./build/agg-haiku-x86.so ./agg-haiku-x86.rebx
#          sudo gzip -9 ./agg-haiku-x86.rebx
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Rebol-AGG-CI-${{github.run_id}}
#          path: ./agg-*.gz
#
#  Haiku-x64:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Download Haiku Rebol-dev container
#        run: docker pull docker.io/oldes/rebol-dev:haiku-x64
#
#      - name: Build all Rebol/AGG for Haiku OS x64
#        run: docker run --rm -v $PWD:/siskin oldes/rebol-dev:haiku-x64 bash -c 'cd /siskin; rebol siskin.r3 Rebol-AGG.nest agg-haiku-x64'
#
#      - name: Compress result before uploading
#        run: |
#          sudo mv ./build/agg-haiku-x64.so ./agg-haiku-x64.rebx
#          sudo gzip -9 ./agg-haiku-x64.rebx
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Rebol-AGG-CI-${{github.run_id}}
#          path: ./agg-*.gz
#
#